---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - kshutdown.io
  resources:
  - shutdowngroups
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - kshutdown.io
  resources:
  - shutdowngroups/finalizers
  verbs:
  - update
- apiGroups:
  - kshutdown.io
  resources:
  - shutdowngroups/status
  verbs:
  - get
  - patch
